import {
  parseTokenSubunits,
  serializeTokenSubunits,
  type TokenSubunitString,
} from "./amount.js";
import {
  ECONOMY_CONTRACT_VERSION,
  parseIsoTimestamp,
  type EconomyContractVersion,
  type IsoTimestamp,
} from "./contracts.js";
import { economyAssert } from "./errors.js";

export const ADMIN_TOKEN_DEFAULT_WINDOW_DAYS = 30;
export const ADMIN_TOKEN_MAXIMUM_WINDOW_DAYS = 365;
export const ADMIN_TOKEN_MAXIMUM_HOURLY_WINDOW_DAYS = 31;
export const ADMIN_TOKEN_MAXIMUM_PAGE_SIZE = 100;
export const ADMIN_TOKEN_MAXIMUM_TREND_POINTS = 1_000;
export const ADMIN_TOKEN_MINIMUM_COHORT_SIZE = 5;
export const ADMIN_TOKEN_ANOMALY_BASELINE_DAYS = 28;

const DAY_MILLISECONDS = 86_400_000;
const HOUR_MILLISECONDS = 3_600_000;

export type AdminTokenActivityTypeV1 =
  | "acquisition"
  | "spend"
  | "reversal"
  | "hold"
  | "failure";

export type AdminTokenActivityStatusV1 =
  | "pending"
  | "held"
  | "settled"
  | "reversed"
  | "failed";

/**
 * Privacy-safe source groupings. Provider names and provider identifiers are
 * intentionally absent from this public reporting boundary.
 */
export type AdminTokenActivitySourceV1 =
  | "paid-purchase"
  | "subscription"
  | "rewarded-activity"
  | "gameplay"
  | "system-adjustment"
  | "unknown";

export type AdminTokenActivitySortV1 =
  | "occurred-at-desc"
  | "amount-absolute-desc";

export type AdminTokenPseudonymAudienceV1 =
  | "admin-token-activity"
  | "mcp-token-activity";

export interface AdminTokenReportingWindowV1 {
  readonly fromInclusive: IsoTimestamp;
  readonly toExclusive: IsoTimestamp;
}

/**
 * One deliberately narrow reporting row. Aliases are generated by a
 * consuming service using its approved audience-separated pseudonym adapter.
 * `safeLabel` must come from a source-owned allowlist, never ledger metadata.
 */
export interface AdminTokenActivityEntryV1 {
  readonly schemaVersion: EconomyContractVersion;
  readonly occurredAt: IsoTimestamp;
  readonly activityType: AdminTokenActivityTypeV1;
  readonly status: AdminTokenActivityStatusV1;
  readonly source: AdminTokenActivitySourceV1;
  readonly amount: TokenSubunitString;
  readonly safeLabel: string;
  readonly rowAlias: string;
  readonly subjectAlias: string;
}

export interface AdminTokenActivityFilterV1 {
  readonly activityTypes?: readonly AdminTokenActivityTypeV1[];
  readonly statuses?: readonly AdminTokenActivityStatusV1[];
  readonly sources?: readonly AdminTokenActivitySourceV1[];
  readonly subjectAlias?: string;
}

export interface AdminTokenActivityPageRequestV1 {
  readonly schemaVersion: EconomyContractVersion;
  readonly limit: number;
  readonly cursor?: string;
  readonly sort: AdminTokenActivitySortV1;
  readonly window: AdminTokenReportingWindowV1;
  readonly filter?: AdminTokenActivityFilterV1;
  /** Fixed by the authenticated host endpoint, never selected by a client. */
  readonly audience: AdminTokenPseudonymAudienceV1;
  /** Fixed by the host's active pseudonym key/version policy. */
  readonly pseudonymVersion: string;
}

export interface AdminTokenActivityResultMetadataV1
  extends AdminTokenReportingWindowV1 {
  readonly schemaVersion: EconomyContractVersion;
  readonly generatedAt: IsoTimestamp;
  readonly sort: AdminTokenActivitySortV1;
  readonly pageLimit: number;
  readonly audience: AdminTokenPseudonymAudienceV1;
  readonly pseudonymVersion: string;
  /** This literal is a machine-testable non-disclosure assertion. */
  readonly rawIdentifiersIncluded: false;
}

export interface AdminTokenActivityPageV1 {
  readonly schemaVersion: EconomyContractVersion;
  readonly entries: readonly AdminTokenActivityEntryV1[];
  readonly hasMore: boolean;
  readonly nextCursor?: string;
  readonly metadata: AdminTokenActivityResultMetadataV1;
}

export type AdminTokenTrendGranularityV1 = "hour" | "day";

export interface AdminTokenTrendRequestV1 {
  readonly schemaVersion: EconomyContractVersion;
  readonly window: AdminTokenReportingWindowV1;
  readonly granularity: AdminTokenTrendGranularityV1;
  readonly activityTypes?: readonly AdminTokenActivityTypeV1[];
}

export interface SuppressedAdminTokenTrendAggregateV1 {
  readonly visibility: "suppressed";
  readonly reason: "cohort-below-minimum";
  readonly threshold: typeof ADMIN_TOKEN_MINIMUM_COHORT_SIZE;
}

export interface ReportedAdminTokenTrendAggregateV1 {
  readonly visibility: "reported";
  readonly distinctSubjects: number;
  readonly activityCount: number;
  readonly signedAmount: TokenSubunitString;
}

export type AdminTokenTrendAggregateV1 =
  | SuppressedAdminTokenTrendAggregateV1
  | ReportedAdminTokenTrendAggregateV1;

export type AdminTokenAnomalyStatusV1 = "normal" | "irregular-spike";

export type AdminTokenAnomalyExplanationCodeV1 =
  | "below-absolute-minimum"
  | "within-baseline-variation"
  | "zero-mad-absolute-threshold-exceeded"
  | "median-mad-and-absolute-threshold-exceeded";

export interface AdminTokenAnomalyIndicatorV1 {
  readonly method: "same-window-median-mad-v1";
  readonly status: AdminTokenAnomalyStatusV1;
  readonly baselineWindowCount: typeof ADMIN_TOKEN_ANOMALY_BASELINE_DAYS;
  readonly medianAmount: TokenSubunitString;
  readonly medianAbsoluteDeviation: TokenSubunitString;
  readonly minimumAbsoluteDelta: TokenSubunitString;
  readonly deviationFromMedian: TokenSubunitString;
  readonly madMultiplierMilli: number;
  readonly explanationCode: AdminTokenAnomalyExplanationCodeV1;
}

export interface CreateAdminTokenAnomalyIndicatorInputV1 {
  readonly observedAmount: TokenSubunitString;
  /** Exactly 28 preceding values for the same time-of-week window. */
  readonly baselineAmounts: readonly TokenSubunitString[];
  readonly minimumAbsoluteDelta: TokenSubunitString;
  /** Fixed-point multiplier where 1,000 represents one MAD. */
  readonly madMultiplierMilli: number;
}

export interface AdminTokenTrendPointV1 {
  readonly schemaVersion: EconomyContractVersion;
  readonly bucketStart: IsoTimestamp;
  readonly bucketEnd: IsoTimestamp;
  readonly activityType: AdminTokenActivityTypeV1;
  readonly aggregate: AdminTokenTrendAggregateV1;
  readonly anomaly?: AdminTokenAnomalyIndicatorV1;
}

export interface AdminTokenTrendResultMetadataV1
  extends AdminTokenReportingWindowV1 {
  readonly schemaVersion: EconomyContractVersion;
  readonly generatedAt: IsoTimestamp;
  readonly granularity: AdminTokenTrendGranularityV1;
  readonly minimumCohortSize: typeof ADMIN_TOKEN_MINIMUM_COHORT_SIZE;
  readonly anomalyBaselineDays: typeof ADMIN_TOKEN_ANOMALY_BASELINE_DAYS;
  /** This literal is a machine-testable non-disclosure assertion. */
  readonly rawIdentifiersIncluded: false;
}

export interface AdminTokenTrendResultV1 {
  readonly schemaVersion: EconomyContractVersion;
  readonly series: readonly AdminTokenTrendPointV1[];
  readonly metadata: AdminTokenTrendResultMetadataV1;
}

/**
 * Provider-neutral read boundary. Authentication, authorization, HMAC aliases,
 * query timeouts, rate limits, and database access remain host responsibilities.
 */
export interface AdminEconomyReportingQueryPortV1 {
  listAdminTokenActivity(
    request: AdminTokenActivityPageRequestV1,
  ): Promise<AdminTokenActivityPageV1>;
  getAdminTokenTrends(
    request: AdminTokenTrendRequestV1,
  ): Promise<AdminTokenTrendResultV1>;
}

const ACTIVITY_TYPES = new Set<AdminTokenActivityTypeV1>([
  "acquisition",
  "spend",
  "reversal",
  "hold",
  "failure",
]);
const ACTIVITY_STATUSES = new Set<AdminTokenActivityStatusV1>([
  "pending",
  "held",
  "settled",
  "reversed",
  "failed",
]);
const ACTIVITY_SOURCES = new Set<AdminTokenActivitySourceV1>([
  "paid-purchase",
  "subscription",
  "rewarded-activity",
  "gameplay",
  "system-adjustment",
  "unknown",
]);
const ACTIVITY_SORTS = new Set<AdminTokenActivitySortV1>([
  "occurred-at-desc",
  "amount-absolute-desc",
]);
const PSEUDONYM_AUDIENCES = new Set<AdminTokenPseudonymAudienceV1>([
  "admin-token-activity",
  "mcp-token-activity",
]);
const TREND_GRANULARITIES = new Set<AdminTokenTrendGranularityV1>([
  "hour",
  "day",
]);
const ALIAS = /^[A-Za-z0-9_-]{16,96}$/u;
const PSEUDONYM_VERSION = /^[A-Za-z0-9][A-Za-z0-9._-]{0,31}$/u;

function assertPlainObject(
  value: unknown,
  label: string,
): void {
  economyAssert(
    typeof value === "object" && value !== null && !Array.isArray(value),
    "INVALID_CONTRACT",
    `${label} must be an object`,
  );
}

function assertExactKeys(
  value: unknown,
  allowedKeys: readonly string[],
  label: string,
): void {
  assertPlainObject(value, label);
  const allowed = new Set(allowedKeys);
  economyAssert(
    Object.keys(value as Readonly<Record<string, unknown>>).every((key) =>
      allowed.has(key),
    ),
    "INVALID_CONTRACT",
    `${label} contains an unsupported or identifying property`,
  );
}

function hasControlCharacters(value: string): boolean {
  return [...value].some((character) => {
    const code = character.charCodeAt(0);
    return code <= 31 || code === 127;
  });
}

function assertSafeDisplayString(value: string, label: string): void {
  economyAssert(
    typeof value === "string"
      && value.trim().length > 0
      && value.length <= 128
      && !hasControlCharacters(value),
    "INVALID_CONTRACT",
    `${label} must be bounded and safe for display`,
  );
}

function assertAlias(value: string, label: string): void {
  economyAssert(
    typeof value === "string" && ALIAS.test(value),
    "INVALID_CONTRACT",
    `${label} must be an opaque pseudonymous alias`,
  );
}

function assertOpaqueCursor(value: string): void {
  economyAssert(
    typeof value === "string"
      && value.length > 0
      && value.length <= 512
      && !hasControlCharacters(value),
    "INVALID_CONTRACT",
    "Admin Token cursor must be a bounded opaque value",
  );
}

function assertUniqueValues<T extends string>(
  values: readonly T[],
  allowed: ReadonlySet<T>,
  label: string,
): void {
  economyAssert(
    Array.isArray(values),
    "INVALID_CONTRACT",
    `${label} must be a list`,
  );
  const unique = new Set(values);
  economyAssert(
    values.length > 0
      && values.length === unique.size
      && values.every((value) => allowed.has(value)),
    "INVALID_CONTRACT",
    `${label} must contain unique supported values`,
  );
}

function absolute(value: bigint): bigint {
  return value < 0n ? -value : value;
}

function compareTextDescending(left: string, right: string): number {
  if (left === right) {
    return 0;
  }
  return left > right ? -1 : 1;
}

function assertReportingWindow(
  window: AdminTokenReportingWindowV1,
  maximumDays = ADMIN_TOKEN_MAXIMUM_WINDOW_DAYS,
): { readonly from: number; readonly to: number } {
  assertExactKeys(
    window,
    ["fromInclusive", "toExclusive"],
    "Admin Token reporting window",
  );
  const from = parseIsoTimestamp(window.fromInclusive);
  const to = parseIsoTimestamp(window.toExclusive);
  economyAssert(
    from < to && to - from <= maximumDays * DAY_MILLISECONDS,
    "INVALID_TIME_WINDOW",
    `Admin Token reporting window must be positive and no longer than ${maximumDays} days`,
  );
  return { from, to };
}

/** Constructs the deterministic 30-day interactive default ending at `asOf`. */
export function createDefaultAdminTokenReportingWindow(
  asOf: IsoTimestamp,
): AdminTokenReportingWindowV1 {
  const to = parseIsoTimestamp(asOf);
  return {
    fromInclusive: new Date(
      to - ADMIN_TOKEN_DEFAULT_WINDOW_DAYS * DAY_MILLISECONDS,
    ).toISOString(),
    toExclusive: new Date(to).toISOString(),
  };
}

/** Validates one narrow row and rejects all undeclared identifier properties. */
export function assertAdminTokenActivityEntry(
  entry: AdminTokenActivityEntryV1,
): void {
  assertExactKeys(
    entry,
    [
      "schemaVersion",
      "occurredAt",
      "activityType",
      "status",
      "source",
      "amount",
      "safeLabel",
      "rowAlias",
      "subjectAlias",
    ],
    "Admin Token activity entry",
  );
  economyAssert(
    entry.schemaVersion === ECONOMY_CONTRACT_VERSION
      && ACTIVITY_TYPES.has(entry.activityType)
      && ACTIVITY_STATUSES.has(entry.status)
      && ACTIVITY_SOURCES.has(entry.source),
    "INVALID_CONTRACT",
    "Unsupported Admin Token activity contract",
  );
  parseIsoTimestamp(entry.occurredAt);
  const amount = parseTokenSubunits(entry.amount);
  economyAssert(
    amount !== 0n
      && (entry.activityType !== "acquisition" || amount > 0n)
      && (entry.activityType !== "spend" || amount < 0n),
    "INVALID_AMOUNT",
    "Admin Token activity amount has an invalid sign or zero value",
  );
  economyAssert(
    (entry.activityType === "failure") === (entry.status === "failed"),
    "INVALID_CONTRACT",
    "Failed rows must use the failure activity type",
  );
  assertSafeDisplayString(entry.safeLabel, "Admin Token activity label");
  assertAlias(entry.rowAlias, "Row alias");
  assertAlias(entry.subjectAlias, "Subject alias");
}

/** Validates a bounded, normalized Admin activity query. */
export function assertAdminTokenActivityPageRequest(
  request: AdminTokenActivityPageRequestV1,
): void {
  assertExactKeys(
    request,
    [
      "schemaVersion",
      "limit",
      "cursor",
      "sort",
      "window",
      "filter",
      "audience",
      "pseudonymVersion",
    ],
    "Admin Token activity request",
  );
  economyAssert(
    request.schemaVersion === ECONOMY_CONTRACT_VERSION
      && Number.isSafeInteger(request.limit)
      && request.limit >= 1
      && request.limit <= ADMIN_TOKEN_MAXIMUM_PAGE_SIZE
      && ACTIVITY_SORTS.has(request.sort)
      && PSEUDONYM_AUDIENCES.has(request.audience)
      && PSEUDONYM_VERSION.test(request.pseudonymVersion),
    "INVALID_CONTRACT",
    "Unsupported or unbounded Admin Token activity request",
  );
  assertReportingWindow(request.window);
  if (request.cursor !== undefined) {
    assertOpaqueCursor(request.cursor);
  }
  if (request.filter === undefined) {
    return;
  }
  assertExactKeys(
    request.filter,
    ["activityTypes", "statuses", "sources", "subjectAlias"],
    "Admin Token activity filter",
  );
  if (request.filter.activityTypes !== undefined) {
    assertUniqueValues(
      request.filter.activityTypes,
      ACTIVITY_TYPES,
      "Admin Token activity types",
    );
  }
  if (request.filter.statuses !== undefined) {
    assertUniqueValues(
      request.filter.statuses,
      ACTIVITY_STATUSES,
      "Admin Token activity statuses",
    );
  }
  if (request.filter.sources !== undefined) {
    assertUniqueValues(
      request.filter.sources,
      ACTIVITY_SOURCES,
      "Admin Token activity sources",
    );
  }
  if (request.filter.subjectAlias !== undefined) {
    assertAlias(request.filter.subjectAlias, "Subject alias filter");
  }
}

function compareActivityEntries(
  left: AdminTokenActivityEntryV1,
  right: AdminTokenActivityEntryV1,
  sort: AdminTokenActivitySortV1,
): number {
  if (sort === "amount-absolute-desc") {
    const leftAmount = absolute(parseTokenSubunits(left.amount));
    const rightAmount = absolute(parseTokenSubunits(right.amount));
    if (leftAmount !== rightAmount) {
      return leftAmount > rightAmount ? -1 : 1;
    }
  }
  const leftTime = parseIsoTimestamp(left.occurredAt);
  const rightTime = parseIsoTimestamp(right.occurredAt);
  if (leftTime !== rightTime) {
    return leftTime > rightTime ? -1 : 1;
  }
  return compareTextDescending(left.rowAlias, right.rowAlias);
}

/** Validates page privacy metadata, bounds, uniqueness, and stable order. */
export function assertAdminTokenActivityPage(
  page: AdminTokenActivityPageV1,
): void {
  assertExactKeys(
    page,
    ["schemaVersion", "entries", "hasMore", "nextCursor", "metadata"],
    "Admin Token activity page",
  );
  assertExactKeys(
    page.metadata,
    [
      "schemaVersion",
      "generatedAt",
      "fromInclusive",
      "toExclusive",
      "sort",
      "pageLimit",
      "audience",
      "pseudonymVersion",
      "rawIdentifiersIncluded",
    ],
    "Admin Token activity metadata",
  );
  economyAssert(
    page.schemaVersion === ECONOMY_CONTRACT_VERSION
      && page.metadata.schemaVersion === ECONOMY_CONTRACT_VERSION
      && typeof page.hasMore === "boolean"
      && page.metadata.rawIdentifiersIncluded === false
      && ACTIVITY_SORTS.has(page.metadata.sort)
      && PSEUDONYM_AUDIENCES.has(page.metadata.audience)
      && PSEUDONYM_VERSION.test(page.metadata.pseudonymVersion)
      && Number.isSafeInteger(page.metadata.pageLimit)
      && page.metadata.pageLimit >= 1
      && page.metadata.pageLimit <= ADMIN_TOKEN_MAXIMUM_PAGE_SIZE,
    "INVALID_CONTRACT",
    "Unsupported Admin Token activity result metadata",
  );
  const window = assertReportingWindow({
    fromInclusive: page.metadata.fromInclusive,
    toExclusive: page.metadata.toExclusive,
  });
  parseIsoTimestamp(page.metadata.generatedAt);
  economyAssert(
    Array.isArray(page.entries)
      && page.entries.length <= page.metadata.pageLimit
      && page.hasMore === (page.nextCursor !== undefined)
      && (!page.hasMore || page.entries.length > 0),
    "INVALID_CONTRACT",
    "Admin Token activity page is unbounded or has inconsistent pagination",
  );
  if (page.nextCursor !== undefined) {
    assertOpaqueCursor(page.nextCursor);
  }

  const rowAliases = new Set<string>();
  let previous: AdminTokenActivityEntryV1 | undefined;
  for (const entry of page.entries) {
    assertAdminTokenActivityEntry(entry);
    const occurredAt = parseIsoTimestamp(entry.occurredAt);
    economyAssert(
      occurredAt >= window.from && occurredAt < window.to,
      "INVALID_TIME_WINDOW",
      "Admin Token activity falls outside the declared result window",
    );
    economyAssert(
      !rowAliases.has(entry.rowAlias),
      "DUPLICATE_IDENTIFIER",
      "Admin Token activity page cannot repeat a row alias",
    );
    rowAliases.add(entry.rowAlias);
    if (previous !== undefined) {
      economyAssert(
        compareActivityEntries(previous, entry, page.metadata.sort) < 0,
        "INVALID_CONTRACT",
        "Admin Token activity page does not use its declared stable sort",
      );
    }
    previous = entry;
  }
}

/**
 * Proves that a result retained the server-normalized window, sort, audience,
 * pseudonym version, page bound, and filters of its request.
 */
export function assertAdminTokenActivityPageForRequest(
  page: AdminTokenActivityPageV1,
  request: AdminTokenActivityPageRequestV1,
): void {
  assertAdminTokenActivityPageRequest(request);
  assertAdminTokenActivityPage(page);
  economyAssert(
    page.metadata.fromInclusive === request.window.fromInclusive
      && page.metadata.toExclusive === request.window.toExclusive
      && page.metadata.sort === request.sort
      && page.metadata.pageLimit === request.limit
      && page.metadata.audience === request.audience
      && page.metadata.pseudonymVersion === request.pseudonymVersion,
    "INVALID_CONTRACT",
    "Admin Token activity result metadata does not match its normalized request",
  );
  const filter = request.filter;
  if (filter === undefined) {
    return;
  }
  economyAssert(
    page.entries.every(
      (entry) =>
        (filter.activityTypes === undefined
          || filter.activityTypes.includes(entry.activityType))
        && (filter.statuses === undefined
          || filter.statuses.includes(entry.status))
        && (filter.sources === undefined
          || filter.sources.includes(entry.source))
        && (filter.subjectAlias === undefined
          || filter.subjectAlias === entry.subjectAlias),
    ),
    "INVALID_CONTRACT",
    "Admin Token activity result contains a row outside its normalized filters",
  );
}

/** Validates a bounded trend request before a reporting adapter runs it. */
export function assertAdminTokenTrendRequest(
  request: AdminTokenTrendRequestV1,
): void {
  assertExactKeys(
    request,
    ["schemaVersion", "window", "granularity", "activityTypes"],
    "Admin Token trend request",
  );
  economyAssert(
    request.schemaVersion === ECONOMY_CONTRACT_VERSION
      && TREND_GRANULARITIES.has(request.granularity),
    "INVALID_CONTRACT",
    "Unsupported Admin Token trend request",
  );
  assertReportingWindow(
    request.window,
    request.granularity === "hour"
      ? ADMIN_TOKEN_MAXIMUM_HOURLY_WINDOW_DAYS
      : ADMIN_TOKEN_MAXIMUM_WINDOW_DAYS,
  );
  if (request.activityTypes !== undefined) {
    assertUniqueValues(
      request.activityTypes,
      ACTIVITY_TYPES,
      "Admin Token trend activity types",
    );
  }
}

function lowerMedian(values: readonly bigint[]): bigint {
  const ordered = [...values].sort((left, right) =>
    left === right ? 0 : left < right ? -1 : 1,
  );
  const value = ordered[Math.floor((ordered.length - 1) / 2)];
  economyAssert(
    value !== undefined,
    "INVALID_CONTRACT",
    "Median requires at least one value",
  );
  return value;
}

function classifyAnomaly(options: {
  absoluteDelta: bigint;
  medianAbsoluteDeviation: bigint;
  minimumAbsoluteDelta: bigint;
  madMultiplierMilli: number;
}): Pick<
  AdminTokenAnomalyIndicatorV1,
  "status" | "explanationCode"
> {
  if (options.absoluteDelta < options.minimumAbsoluteDelta) {
    return {
      status: "normal",
      explanationCode: "below-absolute-minimum",
    };
  }
  if (options.medianAbsoluteDeviation === 0n) {
    return options.absoluteDelta > 0n
      ? {
          status: "irregular-spike",
          explanationCode: "zero-mad-absolute-threshold-exceeded",
        }
      : {
          status: "normal",
          explanationCode: "within-baseline-variation",
        };
  }
  const exceedsBaseline =
    options.absoluteDelta * 1_000n
    >= options.medianAbsoluteDeviation * BigInt(options.madMultiplierMilli);
  return exceedsBaseline
    ? {
        status: "irregular-spike",
        explanationCode: "median-mad-and-absolute-threshold-exceeded",
      }
    : {
        status: "normal",
        explanationCode: "within-baseline-variation",
      };
}

/**
 * Creates an exact, explainable same-window median/MAD indicator. V1 uses the
 * lower median so no fractional TokenSubunit is introduced for 28 samples.
 */
export function createAdminTokenAnomalyIndicator(
  input: CreateAdminTokenAnomalyIndicatorInputV1,
): AdminTokenAnomalyIndicatorV1 {
  assertExactKeys(
    input,
    [
      "observedAmount",
      "baselineAmounts",
      "minimumAbsoluteDelta",
      "madMultiplierMilli",
    ],
    "Admin Token anomaly input",
  );
  economyAssert(
    Array.isArray(input.baselineAmounts)
      && input.baselineAmounts.length === ADMIN_TOKEN_ANOMALY_BASELINE_DAYS
      && Number.isSafeInteger(input.madMultiplierMilli)
      && input.madMultiplierMilli >= 1
      && input.madMultiplierMilli <= 1_000_000,
    "INVALID_CONTRACT",
    "Admin Token anomaly input requires 28 baselines and a bounded fixed-point multiplier",
  );
  const observed = parseTokenSubunits(input.observedAmount);
  const baseline = input.baselineAmounts.map((amount) =>
    parseTokenSubunits(amount),
  );
  const minimum = parseTokenSubunits(input.minimumAbsoluteDelta);
  economyAssert(
    minimum > 0n,
    "INVALID_AMOUNT",
    "Admin Token anomaly absolute minimum must be positive",
  );
  const median = lowerMedian(baseline);
  const medianAbsoluteDeviation = lowerMedian(
    baseline.map((amount) => absolute(amount - median)),
  );
  const deviation = observed - median;
  const classification = classifyAnomaly({
    absoluteDelta: absolute(deviation),
    medianAbsoluteDeviation,
    minimumAbsoluteDelta: minimum,
    madMultiplierMilli: input.madMultiplierMilli,
  });
  return {
    method: "same-window-median-mad-v1",
    ...classification,
    baselineWindowCount: ADMIN_TOKEN_ANOMALY_BASELINE_DAYS,
    medianAmount: serializeTokenSubunits(median),
    medianAbsoluteDeviation: serializeTokenSubunits(medianAbsoluteDeviation),
    minimumAbsoluteDelta: input.minimumAbsoluteDelta,
    deviationFromMedian: serializeTokenSubunits(deviation),
    madMultiplierMilli: input.madMultiplierMilli,
  };
}

function assertAdminTokenAnomalyIndicator(
  anomaly: AdminTokenAnomalyIndicatorV1,
  observedAmount: TokenSubunitString,
): void {
  assertExactKeys(
    anomaly,
    [
      "method",
      "status",
      "baselineWindowCount",
      "medianAmount",
      "medianAbsoluteDeviation",
      "minimumAbsoluteDelta",
      "deviationFromMedian",
      "madMultiplierMilli",
      "explanationCode",
    ],
    "Admin Token anomaly indicator",
  );
  const observed = parseTokenSubunits(observedAmount);
  const median = parseTokenSubunits(anomaly.medianAmount);
  const mad = parseTokenSubunits(anomaly.medianAbsoluteDeviation);
  const minimum = parseTokenSubunits(anomaly.minimumAbsoluteDelta);
  const deviation = parseTokenSubunits(anomaly.deviationFromMedian);
  economyAssert(
    anomaly.method === "same-window-median-mad-v1"
      && anomaly.baselineWindowCount === ADMIN_TOKEN_ANOMALY_BASELINE_DAYS
      && mad >= 0n
      && minimum > 0n
      && Number.isSafeInteger(anomaly.madMultiplierMilli)
      && anomaly.madMultiplierMilli >= 1
      && anomaly.madMultiplierMilli <= 1_000_000
      && deviation === observed - median,
    "INVALID_CONTRACT",
    "Admin Token anomaly arithmetic or method is invalid",
  );
  const expected = classifyAnomaly({
    absoluteDelta: absolute(deviation),
    medianAbsoluteDeviation: mad,
    minimumAbsoluteDelta: minimum,
    madMultiplierMilli: anomaly.madMultiplierMilli,
  });
  economyAssert(
    anomaly.status === expected.status
      && anomaly.explanationCode === expected.explanationCode,
    "INVALID_CONTRACT",
    "Admin Token anomaly classification is inconsistent with its explanation",
  );
}

function assertTrendBucketAlignment(
  start: number,
  end: number,
  granularity: AdminTokenTrendGranularityV1,
): void {
  const expectedDuration =
    granularity === "hour" ? HOUR_MILLISECONDS : DAY_MILLISECONDS;
  const date = new Date(start);
  const aligned =
    date.getUTCMinutes() === 0
    && date.getUTCSeconds() === 0
    && date.getUTCMilliseconds() === 0
    && (granularity === "hour" || date.getUTCHours() === 0);
  economyAssert(
    aligned && end - start === expectedDuration,
    "INVALID_TIME_WINDOW",
    "Admin Token trend bucket is not aligned to its declared granularity",
  );
}

function assertTrendAggregate(
  aggregate: AdminTokenTrendAggregateV1,
): void {
  assertPlainObject(aggregate, "Admin Token trend aggregate");
  if (aggregate.visibility === "suppressed") {
    assertExactKeys(
      aggregate,
      ["visibility", "reason", "threshold"],
      "Suppressed Admin Token trend aggregate",
    );
    economyAssert(
      aggregate.reason === "cohort-below-minimum"
        && aggregate.threshold === ADMIN_TOKEN_MINIMUM_COHORT_SIZE,
      "INVALID_CONTRACT",
      "Suppressed Admin Token trend aggregate has invalid privacy metadata",
    );
    return;
  }
  assertExactKeys(
    aggregate,
    [
      "visibility",
      "distinctSubjects",
      "activityCount",
      "signedAmount",
    ],
    "Reported Admin Token trend aggregate",
  );
  parseTokenSubunits(aggregate.signedAmount);
  economyAssert(
    aggregate.visibility === "reported"
      && Number.isSafeInteger(aggregate.distinctSubjects)
      && aggregate.distinctSubjects >= ADMIN_TOKEN_MINIMUM_COHORT_SIZE
      && Number.isSafeInteger(aggregate.activityCount)
      && aggregate.activityCount >= aggregate.distinctSubjects,
    "INVALID_CONTRACT",
    "Reported Admin Token trend aggregate is invalid or below the privacy threshold",
  );
}

/** Validates suppression, bucket bounds, exact arithmetic, and anomaly details. */
export function assertAdminTokenTrendResult(
  result: AdminTokenTrendResultV1,
): void {
  assertExactKeys(
    result,
    ["schemaVersion", "series", "metadata"],
    "Admin Token trend result",
  );
  assertExactKeys(
    result.metadata,
    [
      "schemaVersion",
      "generatedAt",
      "fromInclusive",
      "toExclusive",
      "granularity",
      "minimumCohortSize",
      "anomalyBaselineDays",
      "rawIdentifiersIncluded",
    ],
    "Admin Token trend metadata",
  );
  economyAssert(
    result.schemaVersion === ECONOMY_CONTRACT_VERSION
      && result.metadata.schemaVersion === ECONOMY_CONTRACT_VERSION
      && TREND_GRANULARITIES.has(result.metadata.granularity)
      && result.metadata.minimumCohortSize
        === ADMIN_TOKEN_MINIMUM_COHORT_SIZE
      && result.metadata.anomalyBaselineDays
        === ADMIN_TOKEN_ANOMALY_BASELINE_DAYS
      && result.metadata.rawIdentifiersIncluded === false
      && Array.isArray(result.series)
      && result.series.length <= ADMIN_TOKEN_MAXIMUM_TREND_POINTS,
    "INVALID_CONTRACT",
    "Unsupported or unbounded Admin Token trend result",
  );
  const window = assertReportingWindow(
    {
      fromInclusive: result.metadata.fromInclusive,
      toExclusive: result.metadata.toExclusive,
    },
    result.metadata.granularity === "hour"
      ? ADMIN_TOKEN_MAXIMUM_HOURLY_WINDOW_DAYS
      : ADMIN_TOKEN_MAXIMUM_WINDOW_DAYS,
  );
  parseIsoTimestamp(result.metadata.generatedAt);

  const pointKeys = new Set<string>();
  let previousKey: string | undefined;
  for (const point of result.series) {
    assertExactKeys(
      point,
      [
        "schemaVersion",
        "bucketStart",
        "bucketEnd",
        "activityType",
        "aggregate",
        "anomaly",
      ],
      "Admin Token trend point",
    );
    economyAssert(
      point.schemaVersion === ECONOMY_CONTRACT_VERSION
        && ACTIVITY_TYPES.has(point.activityType),
      "INVALID_CONTRACT",
      "Unsupported Admin Token trend point",
    );
    const start = parseIsoTimestamp(point.bucketStart);
    const end = parseIsoTimestamp(point.bucketEnd);
    economyAssert(
      start >= window.from && end <= window.to,
      "INVALID_TIME_WINDOW",
      "Admin Token trend bucket falls outside the declared result window",
    );
    assertTrendBucketAlignment(start, end, result.metadata.granularity);
    assertTrendAggregate(point.aggregate);
    economyAssert(
      (point.aggregate.visibility === "reported")
        === (point.anomaly !== undefined),
      "INVALID_CONTRACT",
      "Only reported Admin Token cohorts may include an anomaly indicator",
    );
    if (point.anomaly !== undefined
      && point.aggregate.visibility === "reported") {
      assertAdminTokenAnomalyIndicator(
        point.anomaly,
        point.aggregate.signedAmount,
      );
    }
    const key = `${point.bucketStart}\u0000${point.activityType}`;
    economyAssert(
      !pointKeys.has(key) && (previousKey === undefined || previousKey < key),
      "DUPLICATE_IDENTIFIER",
      "Admin Token trend points must be unique and stably ordered",
    );
    pointKeys.add(key);
    previousKey = key;
  }
}
